_wandb:
    value:
        cli_version: 0.22.3
        e:
            agkvh5pyr9zmo34o7t9wqy7yxf0s4ruu:
                codePath: /home/aipexws5/daniel/hybrid-sys-id/gymnasium_hybrid_sysid.ipynb
                codePathLocal: gymnasium_hybrid_sysid.ipynb
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1967317549056"
                        used: "385476734976"
                email: dtn2@andrew.cmu.edu
                executable: /home/aipexws5/miniconda3/envs/hybrid-sys-id/bin/python
                git:
                    commit: 2ec25e6279eb87d2b09f12dda37b712f8c2f0f92
                    remote: git@github.com:Astronauty/hybrid-sys-id.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-52f2ff53-b19c-7b42-e2b6-753bfecca5e3
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-53535eee-f443-477f-4371-19a8942ec8cb
                host: aipexws5-Lambda-Vector
                memory:
                    total: "134537224192"
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.35
                program: /home/aipexws5/daniel/hybrid-sys-id/gymnasium_hybrid_sysid.ipynb
                python: CPython 3.10.18
                root: /home/aipexws5/daniel/hybrid-sys-id
                startedAt: "2025-11-05T20:14:43.825984Z"
                writerId: agkvh5pyr9zmo34o7t9wqy7yxf0s4ruu
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 34
                - 35
            "4": 3.10.18
            "5": 0.22.3
            "8":
                - 1
            "12": 0.22.3
            "13": linux-x86_64
